feat(jigasi): new JIGASI_MODE variable for sip vs transcriber behavior

diff --git a/jigasi/rootfs/etc/cont-init.d/10-config b/jigasi/rootfs/etc/cont-init.d/10-config
--- a/jigasi/rootfs/etc/cont-init.d/10-config
+++ b/jigasi/rootfs/etc/cont-init.d/10-config
@@ -13,6 +13,17 @@ if [[ "$JIGASI_XMPP_PASSWORD" == "$OLD_JIGASI_XMPP_PASSWORD" ]]; then
     exit 1
 fi
 
+[ -z "$JIGASI_MODE" ] && JIGASI_MODE="sip"
+if [[ "$(echo $JIGASI_MODE | tr '[:upper:]' '[:lower:]')" == "transcriber" ]]; then
+    OLD_JIGASI_TRANSCRIBER_PASSWORD=passw0rd
+    if [[ "$JIGASI_TRANSCRIBER_PASSWORD" == "$OLD_JIGASI_TRANSCRIBER_PASSWORD" ]]; then
+        echo 'FATAL ERROR: Jigasi transcriber password must be changed, check the README'
+        exit 1
+    fi
+    # set random jigasi nickname for the instance if is not set
+    [ -z "${JIGASI_INSTANCE_ID}" ] && export JIGASI_INSTANCE_ID="transcriber-$(date +%N)"
+fi
+
 # set random jigasi nickname for the instance if is not set
 [ -z "${JIGASI_INSTANCE_ID}" ] && export JIGASI_INSTANCE_ID="jigasi-$(date +%N)"
 
@@ -56,7 +67,7 @@ mkdir -pm777 /tmp/transcripts
 chown jigasi:jitsi /tmp/transcripts
 
 # Create Google Cloud Credentials
-if [[ $ENABLE_TRANSCRIPTIONS -eq 1 || $ENABLE_TRANSCRIPTIONS == "true" ]]; then
+if [[ "$(echo $JIGASI_MODE | tr '[:upper:]' '[:lower:]')" == "transcriber" ]]; then
     if [[ -z $GC_PROJECT_ID || -z $GC_PRIVATE_KEY_ID || -z $GC_PRIVATE_KEY || -z $GC_CLIENT_EMAIL || -z $GC_CLIENT_ID || -z $GC_CLIENT_CERT_URL ]]; then
         echo 'Transcriptions: One or more environment variables are undefined'
         exit 1
