sip-jibri: add sip-jibri XMPP domain and user

diff --git a/prosody/rootfs/etc/cont-init.d/10-config b/prosody/rootfs/etc/cont-init.d/10-config
--- a/prosody/rootfs/etc/cont-init.d/10-config
+++ b/prosody/rootfs/etc/cont-init.d/10-config
@@ -54,9 +54,11 @@ fi
 [ -z "${JIBRI_XMPP_USER}" ] && export JIBRI_XMPP_USER=jibri
 [ -z "${JIGASI_XMPP_USER}" ] && export JIGASI_XMPP_USER=jigasi
 [ -z "${JVB_AUTH_USER}" ] && export JVB_AUTH_USER=jvb
+[ -z "${SIP_JIBRI_XMPP_USER}" ] && export SIP_JIBRI_XMPP_USER=sip
 [ -z "${XMPP_DOMAIN}" ] && export XMPP_DOMAIN=meet.jitsi
 [ -z "${XMPP_AUTH_DOMAIN}" ] && export XMPP_AUTH_DOMAIN=auth.meet.jitsi
 [ -z "${XMPP_RECORDER_DOMAIN}" ] && export XMPP_RECORDER_DOMAIN=recorder.meet.jitsi
+[ -z "${XMPP_SIP_DOMAIN}" ] && export XMPP_SIP_DOMAIN=sip.meet.jitsi
 
 prosodyctl --config $PROSODY_CFG register focus $XMPP_AUTH_DOMAIN $JICOFO_AUTH_PASSWORD
 
@@ -93,6 +95,15 @@ if [[ ! -z $JIBRI_RECORDER_PASSWORD ]]; then
         exit 1
     fi
     prosodyctl --config $PROSODY_CFG register $JIBRI_RECORDER_USER $XMPP_RECORDER_DOMAIN $JIBRI_RECORDER_PASSWORD
+fi
+
+if [[ ! -z $SIP_JIBRI_XMPP_PASSWORD ]]; then
+    OLD_SIP_JIBRI_XMPP_PASSWORD=passw0rd
+    if [[ "$SIP_JIBRI_XMPP_PASSWORD" == "$OLD_SIP_JIBRI_XMPP_PASSWORD" ]]; then
+        echo 'FATAL ERROR: Sip-Jibri XMPP password must be changed, check the README'
+        exit 1
+    fi
+    prosodyctl --config $PROSODY_CFG register $SIP_JIBRI_XMPP_USER $XMPP_SIP_DOMAIN $SIP_JIBRI_XMPP_PASSWORD
 fi
 
 if [[ ! -z $JIGASI_XMPP_PASSWORD ]]; then
