Adds turn config.

diff --git a/prosody/rootfs/etc/cont-init.d/10-config b/prosody/rootfs/etc/cont-init.d/10-config
--- a/prosody/rootfs/etc/cont-init.d/10-config
+++ b/prosody/rootfs/etc/cont-init.d/10-config
@@ -25,6 +25,17 @@ if [[ "$(stat -c %U /prosody-plugins-custom)" != "prosody" ]]; then
     chown -R prosody /prosody-plugins-custom
 fi
 
+if [[ "${ENABLE_TURN}" == "1" || "${ENABLE_TURN}" == "true" ]]; then
+    if [[ -z $TURN_HOST ]]; then
+        echo 'FATAL ERROR: TURN_HOST must be set when ENABLE_TURN is true.'
+        exit 1
+    fi
+    if [[ -z $TURN_SECRET ]]; then
+        echo 'FATAL ERROR: TURN_SECRET must be set when ENABLE_TURN is true.'
+        exit 1
+    fi
+fi
+
 cp -r /defaults/* /config
 tpl /defaults/prosody.cfg.lua > $PROSODY_CFG
 tpl /defaults/conf.d/jitsi-meet.cfg.lua > /config/conf.d/jitsi-meet.cfg.lua
