add Let's Encrypt Cloudflare DNS Support

diff --git a/web/rootfs/etc/cont-init.d/10-config b/web/rootfs/etc/cont-init.d/10-config
--- a/web/rootfs/etc/cont-init.d/10-config
+++ b/web/rootfs/etc/cont-init.d/10-config
@@ -10,21 +10,52 @@ mkdir -p \
 # generate keys (maybe)
 if [[ $DISABLE_HTTPS -ne 1 ]]; then
     if [[ $ENABLE_LETSENCRYPT -eq 1 ]]; then
-        if [[ ! -f /etc/letsencrypt/live/$LETSENCRYPT_DOMAIN/fullchain.pem ]]; then
-            if ! certbot certonly \
-                  --noninteractive \
-                  --standalone \
-                  --preferred-challenges http \
-                  -d $LETSENCRYPT_DOMAIN \
-                  --agree-tos \
-                  --email $LETSENCRYPT_EMAIL ; then
+	if [[ $ENABLE_LETSENCRYPT_CLOUDFLARE -ne 1 ]]; then
+            if [[ ! -f /etc/letsencrypt/live/$LETSENCRYPT_DOMAIN/fullchain.pem ]]; then
+                if ! certbot-auto \
+		      certonly \
+		      --no-self-upgrade \
+                      --noninteractive \
+                      --standalone \
+                      --preferred-challenges http \
+                      -d $LETSENCRYPT_DOMAIN \
+                      --agree-tos \
+                       --email $LETSENCRYPT_EMAIL ; then
 
-                echo "Failed to obtain a certificate from the Let's Encrypt CA."
-                # this tries to get the user's attention and to spare the
-                # authority's rate limit:
-                sleep 15
-                echo "Exiting."
-                exit 1
+                    echo "Failed to obtain a certificate from the Let's Encrypt CA."
+                    # this tries to get the user's attention and to spare the
+                    # authority's rate limit:
+                    sleep 15
+                    echo "Exiting."
+                    exit 1
+                fi
+            fi
+        elif [[ $ENABLE_LETSENCRYPT_CLOUDFLARE -eq 1 ]]; then
+            if [[ ! -f /etc/cf.ini ]]; then
+	        echo dns_cloudflare_email = $LETSENCRYPT_CLOUDFLARE_EMAIL > /etc/cf.ini
+                echo dns_cloudflare_api_key = $LETSENCRYPT_CLOUDFLARE_APIKEY >> /etc/cf.ini
+	        chmod 0300 /etc/cf.ini
+	    fi
+            if [[ ! -f /etc/letsencrypt/live/$LETSENCRYPT_DOMAIN/fullchain.pem ]]; then
+                if ! certbot-auto \
+		       certonly \
+		      --no-self-upgrade \
+                      --noninteractive \
+		      --dns-cloudflare \
+		      --dns-cloudflare-credentials /etc/cf.ini \
+		      --dns-cloudflare-propagation-seconds $LETSENCRYPT_CLOUDFLARE_PROPAGATION \
+                      --preferred-challenges dns-01 \
+                      -d $LETSENCRYPT_DOMAIN \
+                      --agree-tos \
+                      --email $LETSENCRYPT_EMAIL ; then
+
+                    echo "Failed to obtain a certificate from the Let's Encrypt CA."
+                    # this tries to get the user's attention and to spare the
+                    # authority's rate limit:
+                    sleep 15
+                    echo "Exiting."
+                    exit 1
+                fi
             fi
         fi
 
